// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLj8x17K5_j3tqNK2mY4vXRPw-WASBcdo',
    appId: '1:835456013103:web:ce5addee44a8550aa207da',
    messagingSenderId: '835456013103',
    projectId: 'elimupepe-4ce6f',
    authDomain: 'elimupepe-4ce6f.firebaseapp.com',
    storageBucket: 'elimupepe-4ce6f.firebasestorage.app',
    measurementId: 'G-P9336EE022',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkgGuEYtpwQ10DFmWgrxPVb74Mpl3qfyc',
    appId: '1:835456013103:android:f78a9b95c51dafb3a207da',
    messagingSenderId: '835456013103',
    projectId: 'elimupepe-4ce6f',
    storageBucket: 'elimupepe-4ce6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEeznemkbzoWovGvr33DdYOdkEHd_0-zM',
    appId: '1:835456013103:ios:a41f1bdf93c4702aa207da',
    messagingSenderId: '835456013103',
    projectId: 'elimupepe-4ce6f',
    storageBucket: 'elimupepe-4ce6f.firebasestorage.app',
    iosBundleId: 'com.loho.elimupepe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEeznemkbzoWovGvr33DdYOdkEHd_0-zM',
    appId: '1:835456013103:ios:a41f1bdf93c4702aa207da',
    messagingSenderId: '835456013103',
    projectId: 'elimupepe-4ce6f',
    storageBucket: 'elimupepe-4ce6f.firebasestorage.app',
    iosBundleId: 'com.loho.elimupepe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLj8x17K5_j3tqNK2mY4vXRPw-WASBcdo',
    appId: '1:835456013103:web:684ae2e60f71c55aa207da',
    messagingSenderId: '835456013103',
    projectId: 'elimupepe-4ce6f',
    authDomain: 'elimupepe-4ce6f.firebaseapp.com',
    storageBucket: 'elimupepe-4ce6f.firebasestorage.app',
    measurementId: 'G-Y25NGYTNF5',
  );
}
