// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiL6CQY6DE0v-BfwdaFDxRViwlxMUJlA0',
    appId: '1:773709142122:web:df9d92a0254e5754709213',
    messagingSenderId: '773709142122',
    projectId: 'elimupepe-8acc4',
    authDomain: 'elimupepe-8acc4.firebaseapp.com',
    storageBucket: 'elimupepe-8acc4.firebasestorage.app',
    measurementId: 'G-VJP2X8X6FX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPs6o82d81V3XLdZSKN8nb2_5X2-VHbuY',
    appId: '1:773709142122:android:8f2d3369dad50cbb709213',
    messagingSenderId: '773709142122',
    projectId: 'elimupepe-8acc4',
    storageBucket: 'elimupepe-8acc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiZDPCTHJ8VlhJQjRHpCYIK3r0FxXbWcM',
    appId: '1:773709142122:ios:f4aa0a082a5d73ba709213',
    messagingSenderId: '773709142122',
    projectId: 'elimupepe-8acc4',
    storageBucket: 'elimupepe-8acc4.firebasestorage.app',
    iosBundleId: 'com.loho.elimupepe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiZDPCTHJ8VlhJQjRHpCYIK3r0FxXbWcM',
    appId: '1:773709142122:ios:f4aa0a082a5d73ba709213',
    messagingSenderId: '773709142122',
    projectId: 'elimupepe-8acc4',
    storageBucket: 'elimupepe-8acc4.firebasestorage.app',
    iosBundleId: 'com.loho.elimupepe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiL6CQY6DE0v-BfwdaFDxRViwlxMUJlA0',
    appId: '1:773709142122:web:405c5f6ce9087c4b709213',
    messagingSenderId: '773709142122',
    projectId: 'elimupepe-8acc4',
    authDomain: 'elimupepe-8acc4.firebaseapp.com',
    storageBucket: 'elimupepe-8acc4.firebasestorage.app',
    measurementId: 'G-G12BZWC272',
  );

}